// <auto-generated />
using System;
using EF_CodeFirst.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_CodeFirst.Migrations
{
    [DbContext(typeof(StudyContext))]
    partial class StudyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EF_CodeFirst.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"), 1L, 1);

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("GradeId");

                    b.HasIndex("StudentId");

                    b.ToTable("Grade");

                    b.HasData(
                        new
                        {
                            GradeId = 1,
                            GradeName = "Odličan",
                            Section = "Matematika",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 2,
                            GradeName = "Vrlo dobar",
                            Section = "Povijest",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 3,
                            GradeName = "Odličan",
                            Section = "Fizika",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 4,
                            GradeName = "Dobar",
                            Section = "Matematika",
                            StudentId = 2
                        },
                        new
                        {
                            GradeId = 5,
                            GradeName = "Vrlo dobar",
                            Section = "Fizika",
                            StudentId = 2
                        },
                        new
                        {
                            GradeId = 6,
                            GradeName = "Odličan",
                            Section = "Hrvatski",
                            StudentId = 2
                        },
                        new
                        {
                            GradeId = 7,
                            GradeName = "Odličan",
                            Section = "Kemija",
                            StudentId = 2
                        });
                });

            modelBuilder.Entity("EF_CodeFirst.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nchar(50)");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("StudentID");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            DateOfBirth = new DateTime(1986, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 1.60m,
                            StudentName = "Petra Ivić",
                            Weight = 55.0
                        },
                        new
                        {
                            StudentID = 2,
                            DateOfBirth = new DateTime(1999, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 1.85m,
                            StudentName = "Ivan Franjić",
                            Weight = 85.0
                        });
                });

            modelBuilder.Entity("EF_CodeFirst.Models.Grade", b =>
                {
                    b.HasOne("EF_CodeFirst.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
